[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x456ec16f14fe79d8593b429ada219662774736e54fb6ae534c22eada51e7dfd7'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
